Repository mineadmin/MineAdmin, pull requests merged in 2024-10, with the labels that each got.

#351 Fix: 修改env 为docker 环境内network
  .env.example
  docker-compose.yml
Labels: bug, size:S, lgtm

#357 update rules auto time
  app/Service/Permission/RoleService.php
Labels: enhancement, size:S, lgtm

#369 fix(refresh_token): 修复刷新token也失效的情况下，导致一直在加载页面转圈
  web/src/utils/http.ts
Labels: bug, size:S

#370 chore(toolbar): 修改 remove 方法的参数
  web/src/utils/toolbars.ts
Labels: size:XS

#371 refactor(user): internationalize error messages in UserListener
  app/Model/ModelListener/UserListener.php
Labels: enhancement, size:XS

#372 refactor: correct typos in language files
  storage/languages/en/role.php
  storage/languages/en/user.php
  storage/languages/zh_CN/role.php
  storage/languages/zh_CN/user.php
  storage/languages/zh_TW/role.php
  storage/languages/zh_TW/user.php
Labels: size:S

#373 feat(config): add ModeNotFoundHandler to exception handlers
  config/autoload/exceptions.php
Labels: enhancement, size:XS

#374 fix(menu、table): 修复菜单新增可一直点击，优化表结构，修复菜单错误提示未翻译的问题
  databases/migrations/2021_04_12_160526_create_user_table.php
  databases/migrations/2021_04_18_215320_create_menu_table.php
  databases/migrations/2021_04_18_215515_create_role_table.php
  storage/swagger/http.json
  web/src/modules/base/locales/en[English].yaml
  web/src/modules/base/locales/zh_CN[简体中文].yaml
  web/src/modules/base/locales/zh_TW[繁體中文].yaml
  web/src/modules/base/views/permission/menu/index.vue
  web/src/modules/base/views/permission/menu/menu-form.vue
Labels: bug, size:S

#376 fix(水印)
  web/src/store/modules/useSettingStore.ts
Labels: size:XS

#378 chore(@mineadmin/pro-table): 升级pro-table到1.0.21，pro-table重构工具栏，开放api可…
  web/package.json
  web/pnpm-lock.yaml
Labels: size:XS

#379 fix(修复菜单新增和编辑逻辑错误)
  web/src/modules/base/views/permission/menu/index.vue
Labels: size:XS

#375 fix(app): stop propagation on mode not found exception
  app/Exception/Handler/ModeNotFoundHandler.php
  storage/languages/zh_CN/result.php
  tests/Feature/Admin/PassportControllerTest.php
  tests/Feature/Repository/UserRepositoryTest.php
Labels: bug, size:S

#381 build(deps): update composer configuration- Remove allow-plugins conf…
  composer.json
  storage/swagger/http.json
Labels: dependencies, size:S, Composer

#382 fix(前端类型错误): 修复前端插件类型定义问题以及usePluginStore部分函数返回值类型错误问题
  web/src/store/modules/usePluginStore.ts
  web/types/global.d.ts
Labels: bug, size:S

#384 chore(pro-table)：升级到1.0.22版，组件增加 `getProTableOptions()` 方法
  web/package.json
  web/pnpm-lock.yaml
Labels: size:XS

#385 build(deps): downgrade doctrine/dbal from 4.1 to 3.6
  composer.json
Labels: dependencies, size:XS, Composer

#386 refactor(admin):重构控制器中的请求数据获取方式
  app/Http/Admin/Controller/AbstractController.php
  app/Http/Admin/Controller/Logstash/UserLoginLogController.php
  app/Http/Admin/Controller/Logstash/UserOperationLogController.php
  app/Http/Admin/Controller/Permission/MenuController.php
  app/Http/Admin/Controller/Permission/RoleController.php
  app/Http/Admin/Controller/Permission/UserController.php
Labels: enhancement, size:M

#388 feat(menu): 更新菜单权限并添加数据中心相关权限
  app/Http/Admin/Controller/AttachmentController.php
  databases/seeders/menu_update_20241029.php
  tests/Feature/Admin/DataCenter/AttachmentControllerTest.php
Labels: bug, enhancement, size:L

#390 feat(swagger): 增加ui界面，通过 `http://127.0.0.1:9503/swagger` 查看接口文档
  config/autoload/swagger.php
  storage/swagger/http.json
  storage/swagger/index.html
Labels: enhancement, size:M

#391 feat(i18n): 添加数据中心相关翻译
  web/src/modules/base/locales/en[English].yaml
  web/src/modules/base/locales/zh_CN[简体中文].yaml
  web/src/modules/base/locales/zh_TW[繁體中文].yaml
Labels: enhancement, size:S, lgtm

#393 chore(ma-form,ma-search)：升级俩组件依赖，优化一些方法入参
  web/package.json
  web/pnpm-lock.yaml
Labels: size:XS

#395 fix(watcher, usePluginStore): 移除监听 api 目录, 修复usePluginStore 类型报错问题
  config/autoload/watcher.php
  web/src/store/modules/usePluginStore.ts
Labels: bug, size:S

#398 Refactor(permission,test)
  app/Http/Admin/Controller/Permission/RoleController.php
  app/Http/Admin/Controller/Permission/UserController.php
  databases/seeders/menu_update_20241031.php
  tests/Feature/Admin/Permission/RoleControllerTest.php
  tests/Feature/Admin/Permission/UserControllerTest.php
  web/src/modules/base/views/permission/role/data/getTableColumns.tsx
  web/src/modules/base/views/permission/user/index.vue
  web/src/store/modules/useRouteStore.ts
  web/src/store/modules/useUserStore.ts
  web/src/utils/recursionGetKey.ts
Labels: enhancement, size:L

#399 refactor(permissions): remove Casbin and refactor permission logic
  app/Command/UpdateCommand.php
  app/Http/Admin/Controller/Permission/RoleController.php
  app/Http/Admin/Controller/PermissionController.php
  app/Http/Admin/Middleware/PermissionMiddleware.php
  app/Http/CurrentUser.php
  app/Model/ModelListener/UserListener.php
  app/Model/Permission/Role.php
  app/Model/Permission/User.php
  app/Schema/RoleSchema.php
  app/Service/Permission/RoleService.php
  app/Service/Permission/UserService.php
  app/Service/PermissionService.php
  composer.json
  config/autoload/dependencies.php
  config/autoload/permission.php
  databases/migrations/2024_10_31_193302_create_user_belongs_role.php
  databases/migrations/2024_10_31_204004_create_role_belongs_menu.php
  databases/seeders/menu_seeder_20240926.php
  databases/seeders/user_seeder_20240926.php
  storage/swagger/http.json
  tests/Feature/Admin/ControllerCase.php
  tests/Feature/Admin/CrudControllerCase.php
  tests/Feature/Admin/DataCenter/AttachmentControllerTest.php
  tests/Feature/Admin/PassportControllerTest.php
  tests/Feature/Admin/Permission/MenuControllerTest.php
  tests/Feature/Admin/Permission/RoleControllerTest.php
  tests/Feature/Admin/Permission/UserControllerTest.php
  tests/Feature/Admin/PermissionControllerTest.php
  tests/Feature/Admin/UserLoginLogControllerTest.php
  tests/Feature/Admin/UserOperationLogControllerTest.php
  tests/Feature/Casbin/ApiTest.php
  tests/Feature/Casbin/FactoryTest.php
  tests/Feature/Command/ApplicationInstallCommandTest.php
  tests/Feature/Repository/AttachmentRepositoryTest.php
  tests/Feature/Repository/MenuRepositoryTest.php
  tests/Feature/Repository/RoleRepositoryTest.php
  tests/Feature/Repository/UserLoginLogRepositoryTest.php
  tests/Feature/Repository/UserOperationLogRepositoryTest.php
  tests/Feature/Repository/UserRepositoryTest.php
Labels: enhancement, size:XL, Composer
