Repository mineadmin/MineAdmin, pull requests merged in 2024-06, with the labels that each got.

#267 Update .env.example
  .env.example
Labels: size:XS

#268 Update README.md
  README.md
Labels: size:S

#269 Update mine-extension.php
  config/autoload/mine-extension.php
Labels: size:XS

#271 feat Auto-generated changelog
  .github/workflows/generator-changelog.yml
Labels: enhancement, size:S

#274 解决部门树状数据时重复问题 #130
  app/System/Mapper/SystemDeptMapper.php
Labels: bug, size:XS, System

#275 修复因 storage_mode是int类型获取文件系统不正确导致无法删除OSS或其他文件系统文件
  app/System/Mapper/SystemUploadFileMapper.php
Labels: bug, size:XS, lgtm, System

#277 fix:修复变量注释不自动提示问题
  api/Listener/ApiLogListener.php
  api/Middleware/VerifyInterfaceMiddleware.php
  app/Setting/Mapper/SettingConfigGroupMapper.php
  app/Setting/Mapper/SettingGenerateTablesMapper.php
  app/System/Listener/UserDeleteListener.php
  app/System/Mapper/SystemAppMapper.php
  app/System/Mapper/SystemUserMapper.php
  app/System/Request/SystemUserRequest.php
Labels: bug, size:M, lgtm, Setting, System

#279 Fix spacing issue in .env.example"
  .env.example
Labels: size:S, lgtm

#281 Remove workflow
  .github/workflows/crontab-cs-fixer.yml
  .github/workflows/generator-changelog.yml
  .github/workflows/pull-request-cs-fixer.yml
  .github/workflows/test.yml
  app/System/Mapper/SystemAppMapper.php
  app/System/Mapper/SystemUserMapper.php
Labels: size:L, System

#282 add docker mysql volumes
  docker-compose.yml
  docker/mysql/57/data/.gitignore
  docker/mysql/57/logs/.gitignore
  docker/mysql/57/my.cnf
Labels: enhancement, size:M, lgtm

#284 feat: 字典分类新增list接口
  app/System/Controller/DataCenter/DictTypeController.php
Labels: enhancement, size:S, System

#285 Release v2.0.1
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  app/System/Controller/DataCenter/DictTypeController.php
  composer.json
Labels: size:M, System, Composer

#287 Using php-cs-fixer parallel
  .php-cs-fixer.php
Labels: size:XS

#289 Add Composer create-project Support
  composer.json
Labels: dependencies, size:XS, Composer

#291 Update Readme
  README.md
Labels: size:XS
