Repository mineadmin/MineAdmin, pull requests merged in 2024-12, with the labels that each got.

#483 styles(ma-tree): 优化 ma-tree 下的 `.mine-tree-node` 样式
  web/src/assets/styles/resources/element.scss
Labels: size:XS

#484 fix(pro-table): 修复pro-table的操作列在使用setTableColumns时，设置无效
  web/package.json
Labels: size:XS

#486 chore(ma-city-select): 优化省市区选择组件
  web/src/components/ma-city-select/index.vue
  web/types/components.d.ts
Labels: size:M

#490 chore(readme.md): 增加战略合作链接，vue-i18n更新到10.0.5
  README.md
  web/package.json
Labels: size:XS

#491 docs(README): 更新组件库链接
  README-en.md
  README.md
Labels: size:XS, lgtm

#493 refactor(menu-tree, useDialog, useDrawer) 优化
  web/src/hooks/useDialog.ts
  web/src/hooks/useDrawer.ts
  web/src/modules/base/views/permission/menu/menu-tree.vue
Labels: size:XS

#495 fix(docker-compose/dockerfile):修复docker-compose只能发布前端一个环境的问题
  docker-compose.yml
  web/Dockerfile
Labels: bug, size:XS, lgtm

#492 fix(Permission): 修复后台权限注解解析逻辑
  app/Http/Admin/Middleware/PermissionMiddleware.php
Labels: bug, size:XS, lgtm

#497 fix(migrate): 修正附件表删除时的表名错误
  databases/migrations/2021_06_24_111216_create_attachment_table.php
Labels: bug, size:XS, lgtm

#499 feat(ma-pro-table & ma-remote-select) :
  web/package.json
  web/src/components/ma-remote-select/index.vue
  web/types/auto-imports.d.ts
Labels: enhancement, size:M

#500 fix 修复表格固定列，表头样式不统一问题；
  web/src/assets/styles/resources/element.scss
Labels: bug, size:XS

#501 ci: add CodeRabbit configuration file
  .coderabbit.yaml
Labels: enhancement, size:S

#502 Fix ai
  .coderabbit.yaml
Labels: size:XS

#504 fix(ma-remote-select): 修复 api 参数未传入 axiosConfig 配置项
  web/src/components/ma-remote-select/index.vue
Labels: size:XS

#505 fix(ma-search): 升级ma-search到1.0.27版本
  web/package.json
Labels: size:XS

#511 fix(table-and-menu): 去掉菜单新增和保存弹框，element plus 的el-tree-select 存在递归报错b…
  web/package.json
  web/src/modules/base/views/permission/menu/index.vue
Labels: size:S

#510 连续按两次 Alt 键，快捷键会失灵
  web/src/layouts/components/bars/tabbar/index.tsx
Labels: bug, size:XS

#513 Feat(ma search)
  web/package.json
Labels: enhancement, size:XS
