Repository mineadmin/MineAdmin, pull requests merged in 2024-08, with the labels that each got.

#318 Fix(phpstan)：修复phpstan(quque0handle-listener)
  app/Listener/QueueHandleListener.php
  composer.json
  phpstan.neon.dist
Labels: size:XS, lgtm, Composer

#319 fix(修复下载插件失败): 修复因space与插件名拼接重叠导致无法下载
  plugin/mine-admin/app-store/src/Service/Service.php
Labels: bug, size:S, lgtm

#321 Fix(WorkFlows)：修复Build
  .github/workflows/build.yml
Labels: bug, size:XS

#320 fixed(ci): 优化 pgsql 环境单元测试用例失败
  .github/workflows/test.yml
  databases/migrations/2021_04_12_160526_create_user_table.php
  databases/seeders/dept_seeder.php
  databases/seeders/user_role_seeder.php
Labels: dependencies, size:L, lgtm, Composer

#323 feature(role): 增加权限管理API
  app/Http/Admin/Controller/Permission/RoleController.php
  app/Http/Admin/Controller/Permission/UserController.php
  app/Http/Admin/Request/Permission/Role/CreateRequest.php
  app/Http/Admin/Request/Permission/Role/SaveRequest.php
  app/Http/Admin/Request/Permission/User/CreateRequest.php
  app/Http/Admin/Request/Permission/User/SaveRequest.php
  app/Model/Permission/Role.php
  app/Schema/RoleSchema.php
  storage/languages/en/role.php
  storage/languages/zh_CN/role.php
  storage/swagger/http.json
  tests/Feature/Admin/ControllerCase.php
  tests/Feature/Admin/Permission/RoleControllerTest.php
  tests/Feature/Admin/Permission/UserControllerTest.php
  tests/Feature/Admin/PermissionControllerCase.php
Labels: enhancement, size:L

#326 feature(dept): 增加部门管理API
  app/Http/Admin/Controller/Permission/DeptController.php
  app/Http/Admin/Request/Permission/DeptRequest.php
  app/Model/Permission/Dept.php
  app/Repository/Permission/DeptRepository.php
  app/Schema/DeptSchema.php
  app/Service/Permission/DeptService.php
  config/config.php
  storage/languages/en/dept.php
  storage/languages/zh_CN/dept.php
  storage/swagger/http.json
  tests/Feature/Admin/Permission/DeptControllerTest.php
Labels: enhancement, size:L

#329 feature(role): 新增角色权限赋予API
  app/Http/Admin/Controller/Permission/RoleController.php
  app/Http/Admin/Middleware/PermissionMiddleware.php
  app/Http/Admin/Request/Permission/Role/BatchGrantPermissionsForRoleRequest.php
  app/Listener/DbQueryExecutedListener.php
  app/Model/Permission/Menu.php
  app/Model/Permission/Role.php
  app/Model/Permission/User.php
  app/Repository/IRepository.php
  app/Service/IService.php
  app/Service/Permission/RoleService.php
  config/config.php
  phpstan.neon.dist
  storage/languages/en/role.php
  storage/languages/zh_CN/role.php
  storage/swagger/http.json
  tests/Feature/Admin/Permission/RoleControllerTest.php
Labels: enhancement, size:L

#330 reactor(role:permission): 补充角色权限授予测试用例
  app/Http/Admin/Controller/Permission/DeptController.php
  app/Http/Admin/Controller/Permission/MenuController.php
  app/Http/Admin/Controller/Permission/PostController.php
  app/Http/Admin/Controller/Permission/RoleController.php
  app/Service/Permission/RoleService.php
  tests/Feature/Admin/Permission/RoleControllerTest.php
Labels: enhancement, size:M

#331 reactor(permission): 完善用户权限API
  app/Http/Admin/Controller/PermissionController.php
  app/Listener/ModelListener/CasbinModelListener.php
  app/Service/Permission/UserService.php
  app/Service/PermissionService.php
  storage/swagger/http.json
  tests/Feature/Admin/PermissionControllerCase.php
  tests/Feature/Admin/PermissionControllerTest.php
Labels: enhancement, size:L

#332 feat(dict): 实现字典类型和数据的CRUD操作
  app/Http/Admin/Controller/Setting/DictDataController.php
  app/Http/Admin/Controller/Setting/DictTypeController.php
  app/Http/Admin/Request/DictDataRequest.php
  app/Http/Admin/Request/DictTypeRequest.php
  app/Kernel/Auth/Jwt.php
  app/Model/Setting/DictData.php
  app/Model/Setting/DictType.php
  app/Repository/Setting/DictDataRepository.php
  app/Repository/Setting/DictTypeRepository.php
  app/Schema/DictDataSchema.php
  app/Schema/DictTypeSchema.php
  app/Service/Setting/DictDataService.php
  app/Service/Setting/DictTypeService.php
  storage/languages/en/dict-data.php
  storage/languages/en/dict-type.php
  storage/languages/zh_CN/dict-data.php
  storage/languages/zh_CN/dict-type.php
  tests/Feature/Admin/Setting/DictDataControllerTest.php
  tests/Feature/Admin/Setting/DictTypeControllerTest.php
Labels: enhancement, size:XL, lgtm

#335 fix(Tests): 修复DictData测试
  databases/seeders/dept_seeder.php
  databases/seeders/user_dept_seeder.php
  databases/seeders/user_seeder.php
Labels: bug, size:M

#334 插件内多语言，内聚
  .github/workflows/build.yml
  .github/workflows/test.yml
  .travis/setup.mysql.sh
  app/Setting/Service/SettingGenerateColumnsService.php
  common/common.php
  docker-compose.yml
  plugin/mine-admin/app-store/languages/en/lang.php
  plugin/mine-admin/app-store/languages/zh_CN/lang.php
  plugin/mine-admin/app-store/src/Service/Service.php
  storage/languages/en/plugin.php
  storage/languages/zh_CN/plugin.php
Labels: enhancement, size:M, lgtm, Setting

#338 feature(upload): 增加资源，资源列表，删除资源接口
  .github/workflows/test.yml
  app/Events/Attachment/UploadEvent.php
  app/Events/User/LoginSuccessEvent.php
  app/Events/User/LogoutEvent.php
  app/Http/Admin/Controller/DataCenter/AttachmentController.php
  app/Http/Admin/Controller/Setting/ConfigController.php
  app/Http/Admin/Controller/Setting/ConfigGroupController.php
  app/Http/Admin/Request/DataCenter/UploadRequest.php
  app/Kernel/Annotation/Auth.php
  app/Kernel/Aspect/AuthAspect.php
  app/Kernel/Auth/Jwt.php
  app/Kernel/Auth/JwtFactory.php
  app/Kernel/Casbin/Adapters/DatabaseAdapter.php
  app/Kernel/Log/UuidRequestIdProcessor.php
  app/Kernel/Support/Filesystem.php
  app/Kernel/Upload/UploadManager.php
  app/Listener/UploadListener.php
  app/Model/DataCenter/Attachment.php
  app/Repository/DataCenter/AttachmentRepository.php
  app/Repository/IRepository.php
  app/Repository/Setting/ConfigGroupRepository.php
  app/Repository/Setting/ConfigRepository.php
  app/Repository/Setting/DictDataRepository.php
  app/Repository/Setting/DictTypeRepository.php
  app/Schema/AttachmentSchema.php
  app/Service/DataCenter/AttachmentService.php
  app/Service/PassportService.php
  app/Service/Permission/MenuService.php
  app/Service/Permission/RoleService.php
  app/Service/Setting/ConfigGroupService.php
  app/Service/Setting/ConfigService.php
  app/Service/Setting/DictDataService.php
  app/Service/Setting/DictTypeService.php
  composer.json
  config/autoload/file.php
  databases/migrations/2021_06_24_111216_create_attachment_table.php
  storage/languages/en/attachment.php
  storage/languages/zh_CN/attachment.php
  storage/swagger/http.json
  tests/Feature/Admin/DataCenter/AttachmentControllerTest.php
  tests/Feature/Admin/Setting/DictDataControllerTest.php
  tests/HttpTestCase.php
Labels: enhancement, size:XL, lgtm

#341 fix(setting_config_seeder): 确保config_select_data为数组类型
  app/Setting/Database/Seeders/Update/setting_config_seeder_update.php
Labels: bug, size:M, lgtm, Setting

#342 jwt登录方式-历史遗留问题-login_type配置错误导致App\System\Listener的match 报错
  app/System/Listener/LoginListener.php
  config/autoload/jwt.php
Labels: bug, size:XS, lgtm, System
