Repository mineadmin/MineAdmin, pull requests merged in 2024-11, with the labels that each got.

#400 feat: 解决上传组件重置为空的情况
  web/src/components/ma-upload-image/index.vue
Labels: bug, size:XS

#401 fix(roleCode): code error
  databases/seeders/user_seeder_20240926.php
Labels: bug, size:XS

#402 feat(maTree)：添加`setCheckStrictly()`，优化角色设置菜单编辑下默认为严格模式
  web/src/components/ma-tree/index.vue
  web/src/modules/base/views/permission/role/setPermissionForm.vue
Labels: size:S

#403 feat(favicon.ico): add favicon.ico file
  web/public/favicon.ico
Labels: enhancement, size:XS

#407 fix: 修复顶级菜单无法被添加的问题
  web/src/modules/base/views/permission/menu/index.vue
Labels: bug, size:XS

#404 refactor(delete): change delete method return type and behavior
  .github/workflows/test.yml
  app/Http/Admin/Controller/Permission/MenuController.php
  app/Http/Admin/Controller/Permission/RoleController.php
  app/Http/Admin/Controller/Permission/UserController.php
  app/Http/Admin/Controller/PermissionController.php
  app/Http/Admin/Middleware/PermissionMiddleware.php
  app/Http/Admin/Request/Permission/BatchGrantPermissionsForRoleRequest.php
  app/Http/CurrentUser.php
  app/Model/Permission/Menu.php
  app/Model/Permission/Role.php
  app/Model/Permission/User.php
  app/Repository/IRepository.php
  app/Service/IService.php
  app/Service/Permission/RoleService.php
  tests/Feature/Admin/Permission/RoleControllerTest.php
Labels: size:L

#408 fix(pro-table, setPermissionForm): 升级pro-table修复classList.add报错bug，修复…
  web/package.json
  web/pnpm-lock.yaml
  web/src/modules/base/views/permission/role/setPermissionForm.vue
Labels: size:XS

#410 chore(front): 退出清除所有tab，ma-dialog新增操作快捷键，ma-tree增加 buttons插槽
  web/src/components/ma-dialog/index.vue
  web/src/components/ma-tree/index.vue
  web/src/store/modules/useUserStore.ts
Labels: size:S

#411 feat(ma-search): 新增监听 enter 按下就快捷提交搜索
  web/package.json
  web/pnpm-lock.yaml
Labels: size:XS

#412 feat(ma-tree): 新增 extra 插槽
  web/src/components/ma-tree/index.vue
Labels: size:M

#413 feat(resource): 增加资源管理器页面，更新依赖
  databases/seeders/menu_update_20241029.php
  storage/swagger/http.json
  web/package.json
  web/pnpm-lock.yaml
  web/src/components/ma-resource-picker/panel.vue
  web/src/components/ma-resource-picker/type.ts
  web/src/modules/base/views/dataCenter/attachment/index.vue
Labels: enhancement, dependencies, size:M

#414 docs(README): remove badges and update content
  README.md
Labels: size:XS

#416 refactor(repository): optimize query handling and update saveById method
  app/Repository/IRepository.php
Labels: enhancement, size:M

#417 remove(mockjs): 移除mockjs
  web/.env.production
  web/mock/attachment.ts
  web/mock/data/attachment.ts
  web/mock/data/userinfo.ts
  web/mock/system.ts
  web/package.json
  web/pnpm-lock.yaml
  web/src/modules/base/views/dashboard/datas/analysis.ts
  web/src/modules/base/views/dashboard/datas/report.ts
  web/vite/index.ts
  web/vite/mock.ts
  web/vite/optimize.ts
Labels: size:XL

#418 add：ma-icon-panel自定义svg包
  web/src/components/ma-icon-picker/ma-icon-panel.vue
Labels: enhancement, size:M

#419 styles(menu): 优化子级菜单激活后，父级菜单高亮
  web/src/layouts/components/menu/item.tsx
  web/src/layouts/style/menu.scss
Labels: size:M

#421 fix(menu): 拼写错误
  web/src/layouts/components/menu/item.tsx
Labels: size:XS

#423 chore(tsconfig): 开启默认允许js
  web/tsconfig.json
Labels: size:XS

#422 fix：资源选择器新增删除方法，修复多语言问题
  web/src/components/ma-resource-picker/panel.vue
  web/src/components/ma-resource-picker/type.ts
Labels: bug, size:L

#424 fix(menu): 修复编辑类型为M的菜单时，按钮权限列表未回显
  web/src/modules/base/views/permission/menu/menu-form.vue
Labels: size:M

#425 chore(tab): 变更标签页新增时检查的key，优化布局文件
  web/src/layouts/index.tsx
  web/src/store/modules/useTabStore.ts
Labels: size:XS

#426 fix(menu): 修复菜单使用bug
  app/Service/Permission/MenuService.php
  web/src/components/ma-tree/index.vue
  web/src/modules/base/views/permission/menu/button-permission.vue
  web/src/modules/base/views/permission/menu/index.vue
  web/src/modules/base/views/permission/menu/menu-form.vue
  web/src/modules/base/views/permission/menu/menu-tree.vue
Labels: size:L

#427 fix(cs-fix): fix 语法
  app/Service/Permission/MenuService.php
Labels: size:XS

#428 styles(样式优化)
  web/src/layouts/style/index.scss
Labels: size:XS

#431 解决Builder没有注册scope的问题
  app/Repository/IRepository.php
Labels: bug, size:XS

#433 fix(menu-btn-permission): 修复菜单按钮列表为空时，未清楚的问题
  web/src/modules/base/views/permission/menu/menu-form.vue
Labels: size:XS

#434 chore(ma-pro-table): 更新ma-pro-table到1.0.27版，pnpm-lock加入忽略列表
  web/.gitignore
  web/package.json
Labels: size:XS

#435 feat(dict-component): 字典组件props增加data参数，可直接传入字典数据集合
  web/src/components/ma-dict-picker/ma-dict-checkbox.vue
  web/src/components/ma-dict-picker/ma-dict-radio.vue
  web/src/components/ma-dict-picker/ma-dict-select.vue
Labels: size:S

#437 feat(tab): useTabStore add changeTabTitle()
  web/src/store/modules/useTabStore.ts
Labels: size:S

#440 feat(readme): 添加鸣谢信息
  web/README.md
Labels: enhancement, size:XS

#439 fix：修增菜单含三级或以上的情况下只有一级菜单有选中样式
  web/src/layouts/components/menu/item.tsx
Labels: bug, size:XS

#441 feat(package): 新增 vue3-ace-editor 依赖作为默认依赖
  web/package.json
Labels: size:XS

#443 fix(main-aside): 修复分栏模式下，菜单激活问题
  web/src/layouts/components/main-aside/index.tsx
Labels: size:XS

#444 fix(bug): 修复添加顶级菜单按钮未初始化id，修复应用商店打开官网链接插件详情页404，优化应用商店图片显示
  web/src/modules/base/views/permission/menu/index.vue
  web/src/plugins/mine-admin/app-store/views/detail.vue
  web/src/plugins/mine-admin/app-store/views/list.vue
Labels: size:S

#447 Reactor(appstore)
  .gitignore
  config/autoload/mine-extension.php
  plugin/mine-admin/app-store/mine.json
  plugin/mine-admin/app-store/src/Service/Service.php
  storage/swagger/http.json
  web/src/plugins/mine-admin/app-store/api/app.ts
  web/src/plugins/mine-admin/app-store/views/detail.vue
  web/src/plugins/mine-admin/app-store/views/index.vue
  web/src/plugins/mine-admin/app-store/views/localList.vue
Labels: size:M

#448 fix(vite-config): 未添加 `base` 参数，导致`VITE_APP_ROOT_BASE` 无效
  web/vite.config.ts
Labels: size:XS

#451 Feat(menu auth)
  app/Model/Permission/Meta.php
  app/Schema/MenuMetaSchema.php
  app/Service/Permission/MenuService.php
  storage/swagger/http.json
  web/package.json
  web/src/assets/images/403.svg
  web/src/assets/images/404.svg
  web/src/layouts/[...all].tsx
  web/src/layouts/[...all].vue
  web/src/locales/en[English].yaml
  web/src/locales/zh_CN[简体中文].yaml
  web/src/locales/zh_TW[繁體中文].yaml
  web/src/modules/base/locales/zh_CN[简体中文].yaml
  web/src/modules/base/views/permission/menu/index.vue
  web/src/modules/base/views/permission/menu/menu-form.vue
  web/src/router/index.ts
  web/src/router/static-routes/rootRoute.ts
  web/src/store/modules/useRouteStore.ts
  web/src/store/modules/useTabStore.ts
Labels: size:L

#452 fix(analyse): fix analyse error
  app/Http/CurrentUser.php
  app/Repository/Permission/MenuRepository.php
  app/Schema/MenuMetaSchema.php
Labels: size:S

#453 fix(cs-fix): fix cs-fix error
  app/Service/Permission/MenuService.php
Labels: size:M

#454 chore(other): 修改类型定义，优化默认静态路由
  web/src/router/static-routes/rootRoute.ts
  web/types/global.d.ts
Labels: size:S

#456 chore(front): 优化修改插件钩子参数
  web/src/plugins/mine-admin/demo/index.ts
  web/src/store/modules/useMenuStore.ts
  web/src/utils/http.ts
  web/types/global.d.ts
Labels: size:M

#457 styles(layout): 优化布局样式
  web/src/layouts/components/header/index.tsx
  web/src/layouts/components/main-aside/index.tsx
  web/src/layouts/components/menu/item.tsx
  web/src/layouts/style/index.scss
  web/src/layouts/style/main-aside.scss
  web/src/store/modules/useMenuStore.ts
Labels: size:M

#458 fix(welcomePage): 修复路由添加 welcomePage 时，自定义数据未覆盖默认数据
  web/src/store/modules/useRouteStore.ts
Labels: size:XS

#459 chore(package): 更新pro-table和search，修复几处小问题
  web/package.json
Labels: size:XS

#461 chore(pro-table): 修复table参数覆盖问题导致参数失效
  web/package.json
Labels: size:XS

#462 refactor(pro-table): 升级到1.0.37，增加暴露搜索事件`@search-submit`, `@search-res…
  web/package.json
Labels: size:XS

#463 fix(front-permission): 修复前端权限检查时如果值为空对象时：`{}`，进入判断条件，导致显示无权限
  web/src/router/index.ts
Labels: size:S

#464 * 字典支持插件目录
  web/src/provider/dictionary/index.ts
Labels: size:XS

#465 feat(iframe): 新增iframe菜单缓存，切换tab时不再重新加载第三方网页
  web/src/layouts/[...all].tsx
  web/src/layouts/components/iframe/index.tsx
  web/src/layouts/components/main-aside/index.tsx
  web/src/layouts/index.tsx
  web/src/modules/base/views/permission/menu/menu-form.vue
  web/src/modules/base/views/uc/index.vue
  web/src/router/index.ts
  web/src/store/modules/useIframeKeepAliveStore.ts
  web/src/store/modules/useRouteStore.ts
  web/types/auto-imports.d.ts
Labels: size:M

#466 fix(pro-table): 修复单元格插件注册后调用无效的问题
  web/package.json
  web/src/plugins/mine-admin/demo/index.ts
Labels: size:XS

#467 fix(pro-table): 修复`requestPage`设置`size`参数无效的bug
  web/package.json
Labels: size:XS

#445 优化 watch
  watch
Labels: bug, size:XS

#468 fix:(menu): 修复提示信息描述不准确
  storage/swagger/http.json
  web/src/modules/base/locales/en[English].yaml
  web/src/modules/base/locales/zh_CN[简体中文].yaml
  web/src/modules/base/locales/zh_TW[繁體中文].yaml
  web/src/modules/base/views/permission/menu/menu-tree.vue
  web/types/auto-imports.d.ts
Labels: bug, size:S

#469 fix(layout): 修复布局与iframe页面问题
  web/src/layouts/components/footer/index.tsx
  web/src/layouts/components/iframe/index.tsx
  web/src/layouts/index.tsx
Labels: size:S

#472 refactor(upload): 抽离上传本地服务器方法到utils里，可被单独调用
  web/src/components/ma-upload-file/index.vue
  web/src/components/ma-upload-image/index.vue
  web/src/utils/uploadLocal.ts
Labels: size:M

#473 refactor(logManage): 优化日志管理批量删除时，弹出提示框确认是否删除
  web/src/modules/base/views/log/userLogin.vue
  web/src/modules/base/views/log/userOperation.vue
Labels: size:S

#475 fix(php-cs)
  app/Http/Admin/Middleware/PermissionMiddleware.php
  app/Http/Common/Result.php
Labels: size:XS

#476 fix(seeder): 修复执行php-cs-fixer造成seeder文件类名错误的问题
  databases/seeders/menu_seeder_20240926.php
  databases/seeders/menu_update_20241029.php
  databases/seeders/menu_update_20241031.php
  databases/seeders/user_seeder_20240926.php
Labels: size:XS

#478 refactor(iframe): 优化 iframe 在tab页关闭和刷新时重新加载iframe页面。
  web/src/layouts/components/iframe/index.tsx
  web/src/store/modules/useTabStore.ts
Labels: size:S

#480 Release v3.0
  .gitignore
  composer.json
  storage/swagger/http.json
Labels: size:S, Composer

#482 fix(swagger): 修复文档引入的 css 和 js 失效问题
  storage/swagger/index.html
Labels: size:XS
