Repository mineadmin/MineAdmin, pull requests merged in 2025-05, with the labels that each got.

#599 feat(ma-dict-picker): support rendering disabled attribute for checkbox, radio, and select components
  web/src/components/ma-dict-picker/ma-dict-checkbox.vue
  web/src/components/ma-dict-picker/ma-dict-radio.vue
  web/src/components/ma-dict-picker/ma-dict-select.vue
Labels: enhancement, size:XS

#601 feat(app-store): support displaying latest version, compatible versions, and demo link on plugin detail page
  web/src/plugins/mine-admin/app-store/views/detail.vue
Labels: enhancement, size:M

#604 fix(MaDictSelect): 支持 el-option-group 分组选项渲染、混合选项
  web/src/components/ma-dict-picker/ma-dict-select.vue
  web/types/global.d.ts
Labels: bug, size:M

#605 fix(menu-form): 修复 菜单管理 页面渲染中递归更新问题
  web/src/modules/base/views/permission/menu/menu-form.vue
Labels: bug, size:S

#610 fix(ma-select-table): 修复单行/多行选中状态判断报错，增强选中判断的安全性
  web/src/components/ma-select-table/index.vue
Labels: bug, size:S

#612 fix(department)：修复部门管理问题
  web/src/modules/base/views/permission/department/data/getTableColumns.tsx
  web/src/modules/base/views/permission/department/index.vue
  web/src/modules/base/views/permission/department/setLeader.vue
Labels: bug, size:S

#611 Fix/real ip
  app/Http/Admin/Request/PassportLoginRequest.php
  app/Http/Common/Event/RequestOperationEvent.php
  app/Http/Common/Middleware/OperationMiddleware.php
  app/Http/Common/Request/Traits/ActionRulesTrait.php
Labels: size:M
