Repository mineadmin/MineAdmin, pull requests merged in 2025-03, with the labels that each got.

#553 fix：Breadcrumb navigation display hidden menu bug
  web/src/layouts/components/bars/breadcrumb/index.tsx
Labels: bug, size:M

#560 fix(MenuService): update create method to return Menu type and correct parent_id reference
  app/Service/Permission/MenuService.php
Labels: bug, size:XS, lgtm

#565 fix: 修正getQuery参数搜索
  app/Repository/IRepository.php
  app/Repository/Permission/MenuRepository.php
  app/Service/Permission/UserService.php
Labels: bug, size:S, lgtm

#566 fix: 优化IRepository的handlePage方法 使得更专注分页格式化
  app/Repository/IRepository.php
Labels: size:S, lgtm

#573 feat: enhance user permission handling and add account status checks
  app/Http/Admin/Middleware/PermissionMiddleware.php
  app/Model/Enums/User/Status.php
  docker-compose.yml
  storage/languages/en/user.php
  storage/languages/zh_CN/user.php
  storage/languages/zh_TW/user.php
Labels: enhancement, size:S

#575 refactor(server): clean up configuration settings by removing comment…
  config/autoload/server.php
Labels: size:XS

#574 feat(download): optimize file download handling
  web/src/utils/download.ts
  web/src/utils/http.ts
Labels: enhancement, size:L
