Repository mineadmin/MineAdmin, pull requests merged in 2025-07, with the labels that each got.

#644 fix: 添加 department_users 查询中的 email 、phone 字段
  app/Repository/Permission/DepartmentRepository.php
Labels: bug, size:XS, lgtm

#645 fix: 修正 DataScopeAspectTest 的命名空间
  tests/Feature/Library/DataPermission/DataScopeAspectTest.php
Labels: bug, size:XS, lgtm

#647 refactor: simplify UserController by removing PassportService dependency and updating login method
  app/Http/Api/Controller/V1/UserController.php
Labels: enhancement, size:S

#651 refactor(repository): 重构列表接口方法
  app/Repository/IRepository.php
Labels: size:XS

#643 chore(workbench): 优化快捷入口路由显示逻辑
  web/src/modules/base/views/dashboard/components/workbench/workbench-fast.vue
Labels: size:S

#655 feat(user): enhance user service with caching and refactor menu filtering logic
  app/Http/CurrentUser.php
  app/Service/Permission/UserService.php
  tests/Feature/Admin/GetTokenTrait.php
  tests/Feature/Admin/PermissionControllerTest.php
Labels: enhancement, size:M

#658 fix(issue-template): 修正 bug 报告模板中的 composer 命令以匹配项目名称
  .github/ISSUE_TEMPLATE/---bug-report.md
Labels: size:XS, lgtm

#659 feat(boring-cyborg): 更新文件路径配置，增加多个模块的权限设置
  .github/boring-cyborg.yml
Labels: enhancement, size:M, lgtm

#660 feat(dialog): 优化全屏交互体验，实现全屏状态可控，并增大全屏按钮热区
  web/src/components/ma-dialog/index.vue
Labels: enhancement, size:XS, lgtm

#668 feat(workflow): 更新 push 和 pull_request 事件的路径配置
  .github/workflows/test.yml
Labels: enhancement, size:S, lgtm, GitHub

#669 Optimize/workflow add cache
  .github/workflows/code-coverage.yml
  .github/workflows/test.yml
Labels: enhancement, size:L, lgtm, GitHub
