Repository mineadmin/MineAdmin, pull requests merged in 2025-01, with the labels that each got.

#517 优化v-copy在http下不能复制的问题
  web/src/directives/copy/index.ts
Labels: enhancement, size:S

#514 chore(http.ts): 优化401状态退出不用等满3秒显得很卡
  web/src/utils/http.ts
Labels: enhancement, size:S

#527 Updated phpstan 2.1
  app/Http/Common/Middleware/OperationMiddleware.php
  app/Service/AttachmentService.php
  app/Service/IService.php
  app/Service/Permission/MenuService.php
  app/Service/Permission/UserService.php
  composer.json
  config/container.php
Labels: dependencies, size:S, Composer

#525 Fix: 修复应用接口文档注解接口查询失败问题
  api/ApiDocController.php
  app/System/Mapper/SystemAppMapper.php
Labels: bug, size:S, lgtm, System

#530 resource panel, update package.json, fix bug
  web/.env.development
  web/package.json
  web/src/components/ma-dialog/index.vue
  web/src/components/ma-resource-picker/panel.vue
  web/src/layouts/components/bars/tabbar/index.tsx
  web/src/modules/base/views/permission/menu/index.vue
  web/src/modules/base/views/permission/role/index.vue
  web/src/modules/base/views/permission/user/index.vue
  web/src/modules/base/views/welcome/index.vue
  web/types/auto-imports.d.ts
Labels: bug, dependencies, size:L

#532 refactor(http): optimize request authorization and validation
  .github/workflows/code-coverage.yml
  .github/workflows/codeql.yml
  .gitignore
  app/Http/Admin/Request/PassportLoginRequest.php
  app/Http/Admin/Request/Permission/BatchGrantPermissionsForRoleRequest.php
  app/Http/Admin/Request/Permission/BatchGrantRolesForUserRequest.php
  app/Http/Admin/Request/Permission/MenuRequest.php
  app/Http/Admin/Request/Permission/PermissionRequest.php
  app/Http/Admin/Request/Permission/RoleRequest.php
  app/Http/Admin/Request/Permission/UserRequest.php
  app/Http/Admin/Request/UploadRequest.php
  app/Http/Api/Request/V1/UserRequest.php
  app/Http/Common/Request/Traits/HttpMethodTrait.php
  app/Http/Common/Request/Traits/NoAuthorizeTrait.php
  app/Model/Permission/Menu.php
  app/Model/Permission/Role.php
  app/Model/Permission/User.php
  tests/Feature/Admin/GetTokenTrait.php
  tests/Feature/Admin/Permission/RoleControllerTest.php
  tests/HttpTestCase.php
Labels: enhancement, size:L

#534 feat: ma-form 更新到 1.0.25
  web/package.json
Labels: size:XS

#535 chore: add APP_DEBUG to .env.example
  .env.example
Labels: size:XS

#538 chore: add ma-key-value component
  web/src/components/ma-key-value/components/form.vue
  web/src/components/ma-key-value/index.vue
  web/src/components/ma-key-value/utils/formatJson.ts
Labels: enhancement, size:L
