Repository mineadmin/MineAdmin, pull requests merged in 2025-04, with the labels that each got.

#578 fix swagger render bug
  config/autoload/swagger.php
Labels: bug, size:XS, lgtm

#579 feat: 新增request动态规则匹配类 ActionRulesTrait
  app/Http/Common/Request/Traits/ActionRulesTrait.php
Labels: enhancement, size:M

#580 feat(user): add password validation rules to UserRequest
  app/Http/Admin/Request/Permission/UserRequest.php
Labels: enhancement, size:XS

#583 fix: add PHPStan ignore directive for ActionRulesTrait
  app/Http/Common/Request/Traits/ActionRulesTrait.php
Labels: size:XS

#585 feat: 前端语言监听第一次初始化
  web/src/layouts/provider.tsx
Labels: enhancement, size:XS

#587 feat:(component) 新增 ma-select-table 组件
  web/src/components/ma-select-table/index.vue
  web/types/components.d.ts
Labels: size:L

#588 Fix：the issue of missing routing parameters when refreshing the page
  web/src/router/index.ts
Labels: bug, size:XS

#589 fix: Cache retrieval logic error does not return default value
  web/src/hooks/useCache.ts
  web/src/layouts/provider.tsx
Labels: bug, size:XS

#591 add tool download.ts
  web/src/utils/download.ts
Labels: size:L

#595 fix(menu): 修复子菜单全部隐藏时父菜单无法点击的问题
  web/src/layouts/components/menu/sub.tsx
Labels: size:S

#593 feat(result): 添加账号禁用相关错误处理和国际化支持
  app/Http/Admin/Middleware/PermissionMiddleware.php
  app/Http/Common/ResultCode.php
  app/Service/PassportService.php
  storage/languages/en/result.php
  storage/languages/zh_CN/result.php
  storage/languages/zh_TW/result.php
  web/src/utils/ResultCode.ts
  web/src/utils/http.ts
Labels: enhancement, size:S

#597 refactor(config): 调整 Swagger 配置修复多个插件 swagger 覆盖问题
  config/autoload/swagger.php
Labels: size:S
