Repository mineadmin/MineAdmin, pull requests merged in 2025-06, with the labels that each got.

#625 更新 ma-search 和 ma-pro-table 依赖版本
  web/package.json
Labels: size:XS

#626 docs(README): Updated contributors graphs link
  README-en.md
  README.md
Labels: size:XS, lgtm

#627 Fix/menu btn permissions
  app/Service/Permission/MenuService.php
  web/src/modules/base/views/permission/menu/menu-form.vue
Labels: bug, size:M

#632 update: 升级 vue-i18n 依赖版本至 11.1.6
  web/package.json
Labels: size:XS

#635 fix(package): 降低vue-i18n版本号
  web/package.json
Labels: bug, dependencies, size:XS, lgtm

#638 Revert pull request
  app/Http/Common/Swagger/Server.php
  docker-compose.yml
  web/package.json
Labels: size:XS
