Repository mineadmin/MineAdmin, pull requests merged in 2025-02, with the labels that each got.

#541 更新注释和docker-compose.yml
  docker-compose.yml
  web/vite.config.ts
Labels: size:M

#543 chore: fix MaRemoteSelect component Slot not displayed
  web/src/components/ma-remote-select/index.vue
Labels: bug, size:XS, lgtm

#544 chore: fix Menu highlight menu field editing cannot save data
  app/Http/Admin/Request/Permission/MenuRequest.php
Labels: bug, size:XS

#545 优化打包镜像
  .dockerignore
  Dockerfile
Labels: enhancement, size:S, lgtm

#549 Upload ext
  web/src/components/ma-resource-picker/panel.vue
  web/src/store/modules/useResourceStore.ts
  web/src/utils/uploadLocal.ts
  web/types/auto-imports.d.ts
  web/types/components.d.ts
  web/types/global.d.ts
Labels: enhancement, size:L
